In [1]:
import pandas as pd
import requests

In [2]:
data = pd.read_csv('Intermediate institute list.csv', encoding='ISO-8859-1')

data = data.drop(columns=['CODE', 'Tier', 'Institure Type'])
data = data.rename(columns={
    'Institute Name': 'name',
    'Managing Authority': 'managing_authority',
    'Latitude': 'latitude',
    'Longitude': 'longitude',
    'Description': 'description',
    'Gender': 'gender',
    'Faculty': 'faculties',
})
data = data.dropna(subset=['name','latitude', 'longitude'])

In [3]:
data['managing_authority'] = data['managing_authority'].str.lower()
data['managing_authority'] = data['managing_authority'].replace(
    to_replace=r'.*government.*',
    value=1,
    regex=True
)
data['managing_authority'] = data['managing_authority'].replace(
    to_replace=r'.*private.*',
    value=2,
    regex=True
)

C:\Users\AhmedAli\AppData\Local\Temp\ipykernel_15344\921603591.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['managing_authority'] = data['managing_authority'].replace(

In [4]:
data['gender'] = data['gender'].str.lower()
data['gender'] = data['gender'].replace(
    to_replace=r'.*co.*',
    value=3,
    regex=True
)
data['gender'] = data['gender'].replace(
    to_replace=r'.*female.*',
    value=2,
    regex=True
)
data['gender'] = data['gender'].replace(
    to_replace=r'.*male.*',
    value=1,
    regex=True
)

C:\Users\AhmedAli\AppData\Local\Temp\ipykernel_15344\3048029431.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['gender'] = data['gender'].replace(

In [5]:
def convert_faculties(faculty):
    if pd.isna(faculty):
        return []
    faculty = faculty.split(',')
    new_faculty = []
    for f in faculty:
        f = f.strip().upper()
        new_f = ""
        for i in f:
            if i.isalpha():
                new_f += i
            else:
                new_f += '-'
        new_faculty.append(new_f)
    return new_faculty
data['faculties'] = data['faculties'].apply(convert_faculties)
data['faculties'] = data['faculties'].apply(lambda x: [f for f in x if f != ''])

In [6]:
data['description'] = data['description'].str.strip() if data['description'].notna().any() else ''

In [7]:
def create_object(row):
    obj = {
        "name": row['name'],
        "managing_authority": row['managing_authority'],
        "latitude": row['latitude'],
        "longitude": row['longitude'],
        "faculties": [],
        "tcf_rating": 0.0,
        "description": row['description']
    }
    for faculty in row['faculties']:
        obj['faculties'].append({
            "name": faculty,
            "gender": row['gender']
        })

    return obj

In [8]:
token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0Njk5NzU3NywianRpIjoiMzkxNDgyYWUtYzQ2OS00ZDEwLTgwYjQtZTRlYjExZGExZGFlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY4MGU0MzBjZThkZTE5MzJhNWRhNjYxZiIsIm5iZiI6MTc0Njk5NzU3NywiY3NyZiI6IjA5MjUwMjc5LTQxYTMtNDEwOS1iODUyLWE3MDY3NDI5NGEyOSIsImV4cCI6MTc0NzYwMjM3Nywicm9sZSI6MSwiZW1haWwiOiJhaG1lZGFsaW5pY29iYXJAZ21haWwuY29tIiwiZGV2aWNlX2lkIjpudWxsfQ.-OhVvxOAWhbfB9VxZOPHztluauy7UnuLoxznlKlRiLU"
url = "http://104.248.233.145/api/institute"

In [10]:
# loop through the dataframe and send a POST request for each row
for index, row in data.iterrows():
    obj = create_object(row)
    response = requests.post(url, json=obj, headers={"Authorization": token})
    if response.status_code == 201:
        print(f"Row {index} created successfully.")
    else:
        print(f"Row {index} failed to create. Status code: {response.status_code}, Response: {response.text}")
        print(obj)

Row 0 created successfully.
Row 1 created successfully.
Row 2 created successfully.
Row 3 created successfully.
Row 4 created successfully.
Row 5 created successfully.
Row 6 created successfully.
Row 7 created successfully.
Row 8 created successfully.
Row 9 created successfully.
Row 10 created successfully.
Row 11 created successfully.
Row 12 created successfully.
Row 13 created successfully.
Row 14 created successfully.
Row 15 created successfully.
Row 16 created successfully.
Row 17 created successfully.
Row 18 created successfully.
Row 19 created successfully.
Row 20 created successfully.
Row 21 created successfully.
Row 22 created successfully.
Row 23 created successfully.
Row 24 created successfully.
Row 25 created successfully.
Row 26 created successfully.
Row 27 created successfully.
Row 28 created successfully.
Row 29 created successfully.
Row 30 created successfully.
Row 31 created successfully.
Row 32 created successfully.
Row 33 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. DEGREE BOYS COLLEGE, 11-A, NORTH KARACHI, KARACHI', 'managing_authority': 1, 'latitude': 24.9841839, 'longitude': 67.0561477, 'faculties': [{'name': 'PRE-MEDICAL', 'gender': 1}, {'name': 'PRE-ENGINEERING', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/Fu1wPeYEFVdCvu4m8'}
Row 34 created successfully.
Row 35 created successfully.
Row 36 created successfully.
Row 37 created successfully.
Row 38 created successfully.
Row 39 created successfully.
Row 40 created successfully.
Row 41 created successfully.
Row 42 created successfully.
Row 43 created successfully.
Row 44 created successfully.
Row 45 created successfully.
Row 46 created successfully.
Row 47 created successfully.
Row 48 created successfully.
Row 49 created successfully.
Row 50 created successfully.
Row 51 created successfully.
Row 52 created successfully.
Row 53 created successfully.
Row 54 created successfully.
Row 55 created successfully.
Row 56 created successfully.
Row 57 created successfully.
Row 58 created successfully.
Row 59 created successfully.
Row 60 created successfully.
Row 61 created successfully.
Row 62 created successfully.
Row 63 created successfully.
Row 64 created successfully.
Row 65 created successfully.
Row 66 created successfully.
Row 67 created successfully.
Row 68 created successfully.
Row 69 created successfully.
Row 70 created successfully.
Row 71 created successfully.
Row 72 created successfully.
Row 73 created successfully.
Row 74 created successfully.
Row 75 created successfully.
Row 76 created successfully.
Row 77 created successfully.
Row 78 created successfully.
Row 79 created successfully.
Row 80 created successfully.
Row 81 created successfully.
Row 82 created successfully.
Row 83 created successfully.
Row 84 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'SHAHEED MOHTARMA BENAZIR BHUTTO GOVT. DEGREE GIRLS COLLEGE AZAM BASTI', 'managing_authority': 1, 'latitude': 24.8448689, 'longitude': 67.0704137, 'faculties': [{'name': 'PRE-MEDICAL', 'gender': 2}, {'name': 'PRE-ENGINEERING', 'gender': 2}, {'name': 'HUMANITIES', 'gender': 2}, {'name': 'COMMERCE', 'gender': 2}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/FJFMTJfcUv9Gyfqw8'}
Row 85 created successfully.
Row 86 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. KARACHI COLLEGE FOR WOMEN', 'managing_authority': 1, 'latitude': 24.858272, 'longitude': 67.0154717, 'faculties': [{'name': 'PRE-MEDICAL', 'gender': 2}, {'name': 'PRE-ENGINEERING', 'gender': 2}, {'name': 'HUMANITIES', 'gender': 2}, {'name': 'COMMERCE', 'gender': 2}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/35t4ap8kMxFYgWf69'}
Row 87 created successfully.
Row 88 created successfully.
Row 89 created successfully.
Row 90 created successfully.
Row 91 created successfully.
Row 92 created successfully.
Row 93 created successfully.
Row 94 created successfully.
Row 95 created successfully.
Row 96 created successfully.
Row 97 created successfully.
Row 98 created successfully.
Row 99 created successfully.
Row 100 created successfully.
Row 101 created successfully.
Row 102 created successfully.
Row 103 created successfully.
Row 104 created successfully.
Row 105 created successfully.
Row 106 created successfully.
Row 107 created successfully.
Row 108 created successfully.
Row 109 created successfully.
Row 110 created successfully.
Row 111 created successfully.
Row 112 created successfully.
Row 113 created successfully.
Row 114 created successfully.
Row 115 created successfully.
Row 116 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. DEGREE GIRLS COLLEGE, PAK COLONY ASIFABAD, WEST, KARACHI', 'managing_authority': 1, 'latitude': 24.8980186, 'longitude': 67.0111271, 'faculties': [{'name': 'PRE-MEDICAL', 'gender': 2}, {'name': 'PRE-ENGINEERING', 'gender': 2}, {'name': 'HUMANITIES', 'gender': 2}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/y26tHDojTSEwiUyd8'}
Row 117 created successfully.
Row 118 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT, JAMIA MILLIA DEGREE COLLEGE ( EVENING)', 'managing_authority': 1, 'latitude': 24.8727089, 'longitude': 67.1740713, 'faculties': [{'name': 'COMPUTER-SCIENCE', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/cSvXQvt33RrDR3AF7'}
Row 119 created successfully.
Row 120 created successfully.
Row 121 created successfully.
Row 122 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'ALLAMA IQBAL GOVT DEGREE BOYS ARTS AND COMMERCE COLLEGE NO.02', 'managing_authority': 1, 'latitude': 24.9059582, 'longitude': 67.1859207, 'faculties': [{'name': 'HUMANITIES', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/HNH7Lx3wPFxH7cBw7'}
Row 123 created successfully.
Row 124 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'S.M. GOVT. ARTS AND COMMERCE COLLEGE MORNING', 'managing_authority': 1, 'latitude': 24.8536917, 'longitude': 67.0135421, 'faculties': [{'name': 'HUMANITIES', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/6NFj6PGcnYbbuehR9'}
Row 125 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. SUPERIOR COMMERCE COLLEGE, EVENING', 'managing_authority': 1, 'latitude': 24.8843406, 'longitude': 67.1452558, 'faculties': [{'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/CkTNnwVS7NsZYR6ZA'}
Row 126 created successfully.
Row 127 created successfully.
Row 128 created successfully.
Row 129 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'HAJI ABDULLAH HAROON GOVT. DEGREE COLLEGE EVENING', 'managing_authority': 1, 'latitude': 24.8567857, 'longitude': 66.9890642, 'faculties': [{'name': 'HUMANITIES', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/swpRuR4LmLpNXSD18'}
Row 130 created successfully.
Row 131 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'SIRAJUDULLAH GOVT. DEGREE COLLEGE EVENING', 'managing_authority': 1, 'latitude': 24.9152559, 'longitude': 67.048312, 'faculties': [{'name': 'HUMANITIES', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/ReeJkU8W8bRt1f266'}
Row 132 created successfully.
Row 133 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'AISHA BAWANI GOVT COLLEGE EVENING', 'managing_authority': 1, 'latitude': 24.8575526, 'longitude': 67.0542345, 'faculties': [{'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/48riUC5w1u9K93Be6'}
Row 134 created successfully.
Row 135 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. NATIONAL COLLEGE ( EVENING)', 'managing_authority': 1, 'latitude': 24.8847812, 'longitude': 67.0576756, 'faculties': [{'name': 'HUMANITIES', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/uKQzZm859B5Lvz4B7'}
Row 136 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. COLLEGE OF COMMERCE AND ECONOMICS NO 2', 'managing_authority': 1, 'latitude': 24.8475794, 'longitude': 67.0205448, 'faculties': [{'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/zaY2oNNBhUPTbCWu6'}
Row 137 created successfully.
Row 138 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. DEGREE ARTS AND COMMERCE COLLEGE LANDHI EVENING', 'managing_authority': 1, 'latitude': 24.8252746, 'longitude': 67.172056, 'faculties': [{'name': 'HUMANITIES', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/fohtjv2Qm38y9M6d6'}
Row 139 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. ISLAMIA ARTS AND COMMERCE COLLEGE No.2', 'managing_authority': 1, 'latitude': 24.9631875, 'longitude': 67.0737532, 'faculties': [{'name': 'HUMANITIES', 'gender': 1}, {'name': 'COMMERCE', 'gender': 1}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/3s8c3bHdTbBeHkML8'}
Row 140 created successfully.
Row 141 created successfully.
Row 142 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. GIRLS DEGREE COLLEGE (KMC PARK) LIAQUATABAD KARACHI', 'managing_authority': 1, 'latitude': 24.9017467, 'longitude': 67.0419696, 'faculties': [{'name': 'HUMANITIES', 'gender': 2}, {'name': 'COMMERCE', 'gender': 2}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/P7tDbWAhdq9jceba9'}
Row 143 created successfully.
Row 144 created successfully.
Row 145 created successfully.
Row 146 created successfully.
Row 147 created successfully.
Row 148 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'GOVT. DEGREE GIRLS COLLEGE GULZAR E HIJRI SCHEME -33', 'managing_authority': 1, 'latitude': 24.9427279, 'longitude': 67.0959057, 'faculties': [{'name': 'PRE-MEDICAL', 'gender': 2}, {'name': 'PRE-ENGINEERING', 'gender': 2}, {'name': 'HUMANITIES', 'gender': 2}, {'name': 'HOME-ECONOMICS', 'gender': 2}, {'name': 'COMPUTER-SCIENCE', 'gender': 2}, {'name': 'COMMERCE', 'gender': 2}], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/n3ngFTiBEtj5zqDz6'}
Row 149 created successfully.
Row 150 created successfully.
Row 151 created successfully.
Row 152 created successfully.
Row 153 created successfully.
Row 154 created successfully.
Row 155 created successfully.
Row 156 created successfully.
Row 157 created successfully.
Row 158 created successfully.
Row 159 created successfully.
Row 160 created successfully.
Row 161 created successfully.
Row 162 created successfully.
Row 163 created successfully.
Row 164 created successfully.
Row 165 created successfully.
Row 166 created successfully.
Row 167 created successfully.
Row 168 created successfully.
Row 169 created successfully.
Row 170 created successfully.
Row 171 created successfully.
Row 172 created successfully.
Row 173 created successfully.
Row 174 created successfully.
Row 175 created successfully.
Row 176 created successfully.
Row 177 created successfully.
Row 178 failed to create. Status code: 500, Response: {"success": false, "message": "Internal server error", "data": null}
{'name': 'The Hunar Foundation, Kharian', 'managing_authority': 2, 'latitude': 31.4319854, 'longitude': 74.460756, 'faculties': [], 'tcf_rating': 0.0, 'description': 'https://maps.app.goo.gl/nVqf16GA7RPr6ojj9'}
Row 179 created successfully.
Row 180 created successfully.
Row 181 created successfully.
Row 182 created successfully.
Row 183 created successfully.
Row 184 created successfully.
Row 185 created successfully.
Row 186 created successfully.
Row 187 created successfully.